#name: Job Default
#
#on:
#  push:
#    branches:
#      - dev
#
#jobs:
#  test:
#    name: Node.js Test
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: 20
#
#      - name: Install dependencies
#        working-directory: ./node-app
#        run: npm install
#
#      - name: Run tests
#        working-directory: ./node-app
#        run: npm test


#name: Runners (Matrix-1)
#
#on:
#  push:
#    branches:
#      - dev
#
#jobs:
#  matrix-1:
#    name: Node.js matrix-1
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [ 14, 16, 18 ]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - name: Install dependencies
#        working-directory: ./node-app
#        run: npm install
#
#      - name: Run tests
#        working-directory: ./node-app
#        run: npm test

#name: Runners (Matrix-2)
#
#on:
#  push:
#    branches:
#      - dev
#
#jobs:
#  matrix-1:
#    name: Node.js matrix-2
#
#    strategy:
#      matrix:
#        os: [ ubuntu-latest, windows-latest, macos-latest ]
#        node-version: [ 14, 16, 18 ]
#
#    runs-on: ${{ matrix.os }}
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - name: Install dependencies
#        working-directory: ./node-app
#        run: npm install
#
#      - name: Run tests
#        working-directory: ./node-app
#        run: npm test

name: Runners (Docker image runner)

on:
  push:
    branches:
      - dev

jobs:
  docker-image-runner:
    runs-on: ubuntu-latest
    container:
      image: node:12.18.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependancies
        working-directory: ./node-app
        run: npm install

      - name: Run tests
        working-directory: ./node-app
        run: npm test
