name: Job Default

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Node.js Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./node-app
        run: |
          npm install

      - name: Run tests
        working-directory: ./node-app
        run: |
          npm test 
