name: Push Event 2 exercice

on:
  push:
    branches-ignore:
    - staging
jobs:
  push-event:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello chacal
        run: |
          echo "Hello ${{ github.actor }} gros chacal!"
