name: Event 4 exercice

on:
  push:
    paths:
      - '**.ts'

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello Message
        run: |
          echo "Hello ${{ github.actor }} Jallu , change pas le ts stp fdp!"
